### ISSUE TITLE
docker: processor-sdk-doc: What's unknown/unknown type? 

### ISSUE THREAD

**Issue by cshilwant** [TexasInstruments/processor-sdk-doc#11]
What's `unknown/unknown` under https://github.com/TexasInstruments/processor-sdk-doc/pkgs/container/processor-sdk-doc ?

![image](https://github.com/user-attachments/assets/e6ffb503-187d-49a7-9fd4-6b4b74aaa509)

**Comment by StaticRocket** [comment]
That's a build attestation artifact.

https://docs.docker.com/build/metadata/attestations/attestation-storage/

**Comment by cshilwant** [comment]
I see. Only way to avoid it would be skipping metadata-action & just continue building with docker build.
But that's not the motive. 
The issue can be ignored & closed
