### ISSUE TITLE
provide a documentation contribution guidelines doc

### ISSUE THREAD

**Issue by nmenon** [TexasInstruments/processor-sdk-doc#6]
Provide a contributions guideline doc that informs new users how to contribute to the project, licensing permitted, commit message style etc

**Comment by cshilwant** [comment]
@nmenon Thanks for your suggestions.
We are already working on to add the guidelines on how to contribute to the project, licensing permitted, commit message style etc

Stay Tuned!

**Comment by nmenon** [comment]
you can use https://www.conventionalcommits.org/en/v1.0.0/ as well.
