### ISSUE TITLE
Create a CODEOWNERS file to auto assign reviewers

### ISSUE THREAD

**Issue by DhruvaG2000** [TexasInstruments/processor-sdk-doc#8]
We need to add a CODEOWNERS file [1] to this repo so that we can auto assign reviewers.

[1] https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by DhruvaG2000** [comment]
We should take inspiration from how it's being done in Zephyr: https://github.com/zephyrproject-rtos/zephyr/blob/main/CODEOWNERS

If you see their file too has "Errors" according to github, but they don't use the "Github" way of assiging reviewers it seems like they do some amount of scripting here: https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/workflows/assigner.yml which ultimately runs a python script:
https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/set_assignees.py

This script then parses https://github.com/zephyrproject-rtos/zephyr/blob/main/MAINTAINERS.yml and then auto assigns reviewers.

**Comment by StaticRocket** [comment]
Found a workflow that does the same thing the zephyr project tool was doing, but without reusing the CODEOWNERS format, so it doesn't actually conflict with GitHub right now.

We should be able to run with this until https://github.com/orgs/community/discussions/23042 is resolved.

**Comment by DhruvaG2000** [comment]
@StaticRocket  no no.. We don't even really need to use CODEOWNERS if you see zephyr python script, it parses the maintainers file. So there's no conflict.

**Comment by cshilwant** [comment]
>  until https://github.com/orgs/community/discussions/23042 is resolved.

@StaticRocket I don't think they are thinking to resolve it. 
I mean the thread was last responded by a GitHub team in 2019 🙂

**Comment by StaticRocket** [comment]
I have faith. We've had bugs open for longer durations. :)

**Comment by cshilwant** [comment]
Re-opening this issue (which got auto closed) since https://github.com/TexasInstruments/processor-sdk-doc/pull/32 will be the used as well to assign pull requests to default reviewers based on sections
